server:
  port: ${PORT:8080}

spring:
  application:
    name: plant-care-service
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


openweather:
  api:
    key: ${OPENWEATHER_API_KEY:}

weather:
  api-key: ${OPENWEATHER_API_KEY:${WEATHER_API_KEY:}}
